# Generated by Django 3.0.3 on 2020-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='description',
        ),
        migrations.RemoveField(
            model_name='list',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='list',
            name='venue',
        ),
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=120, verbose_name='dbRecord'),
        ),
    ]
