# Generated by Django 3.0.3 on 2020-02-12 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200212_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='name',
        ),
        migrations.AddField(
            model_name='list',
            name='anotherRandomEntry',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Second random entry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='list',
            name='randomEntry',
            field=models.CharField(default=django.utils.timezone.now, max_length=120, verbose_name='Random entry'),
            preserve_default=False,
        ),
    ]
