# Generated by Django 3.0.3 on 2020-02-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200212_1804'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='list',
            new_name='listPage',
        ),
    ]
