# Generated by Django 3.0.3 on 2020-02-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200212_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='listPage',
            new_name='listModel',
        ),
    ]
