# Generated by Django 3.0.3 on 2020-02-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200215_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listmodel',
            name='anotherRandomEntry',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='listmodel',
            name='randomEntry',
            field=models.CharField(max_length=120),
        ),
    ]
